services:
  - type: web
    name: yawmiy-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PHONEPE_MERCHANT_ID
        sync: false
      - key: PHONEPE_SALT_KEY
        sync: false
      - key: PHONEPE_SALT_INDEX
        sync: false
      - key: PHONEPE_BASE_URL
        sync: false
      - key: APP_BASE_URL
        sync: false
      - key: PHONEPE_CLIENT_ID
        sync: false
      - key: PHONEPE_CLIENT_SECRET
        sync: false
      - key: PHONEPE_CLIENT_VERSION
        value: "1"
      - key: PHONEPE_ENV
        value: production
      - key: PHONEPE_WEBHOOK_USERNAME
        sync: false
      - key: PHONEPE_WEBHOOK_PASSWORD
        sync: false

databases:
  - name: yawmiy-db
    plan: starter
    databaseName: yawmiy
    user: yawmiy_user






